export const SET_LOADING = "SET_LOADING";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ONE_SUCCESS = "FETCH_ONE_SUCCESS";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const FETCH_ERROR = "FETCH_ERROR";
export const MODAL_HANDLER = "MODAL_HANDLER";
