export const FETCH_ERROR = "FETCH_ERROR";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ONE_SUCCESS = "FETCH_ONE_SUCCESS";
export const SET_LOADING = "SET_LOADING";
export const MODAL_HANDLER = "MODAL_HANDLER";
